set_command = """
hyprctl hyprpaper reload ,"{out}"

cat << EOF > ~/.config/hypr/colors.css
@define-color --color-fg {colors.second_accent_color};
@define-color --color-bg {colors.accent_color};
@define-color --color-accent {colors.second_accent_color_inverted};
EOF

touch -m ~/.config/hypr/waybar/style.css
touch -m ~/.config/hypr/wofi/style.css
"""

reset_command = """
# Set wallpaper
hyprctl hyprpaper reload ,~/Pictures/wallpapers/gruvbox-girl.png

cat << EOF > ~/.config/hypr/colors.css
@define-color --color-bg #282828;
@define-color --color-fg #EBDBB2;
@define-color --color-accent #D65D0E;
EOF

touch -m ~/.config/hypr/waybar/style.css
touch -m ~/.config/hypr/wofi/style.css
"""
log_level = "DEBUG"

# Background
[[layers]]
name = "background"

[[layers.processors]]
name = "fit"
args = { width = "{screen.width}", height = "{screen.height}" }

[[layers.processors]]
name = "gaussian_blur"
args = { radius = "20" }

# Foreground
[[layers]]
name = "foreground"

[[layers.processors]]
name = "resize"
args = { width = 600, height = 600 }
