root = "dotfiles"

[files]
mise = "~/.config/mise"
".mbg.toml" = "~/.config/.mbg.toml"
".zshenv" = "~/.zshenv"
"config.ini" = "~/.config/gammastep/config.ini"
hypr = "~/.config/hypr"
".zfunc" = "~/.zfunc"
kitty = "~/.config/kitty"
wallpapers = "~/Pictures/wallpapers"
nvim = "~/.config/nvim"
".zshrc" = "~/.zshrc"
"keyboard-layout.json" = "~/.config/keyboard-layout.json"
".gitconfig" = "~/.gitconfig"
